from pydantic import BaseModel, Field


class EntrySummary(BaseModel):
    """
    Lightweight entry shape used in the sidebar list.
    No body_text — we don't need to load file content just to list entries.
    """

    node_id: str
    title_or_name: str
    created_at: str


class EntryDetail(BaseModel):
    """Full entry shape returned when a user opens an entry."""

    node_id: str
    title_or_name: str
    created_at: str
    body_text: str


class EntryCreate(BaseModel):
    """
    Pydantic model for the POST /entries request body.
    Mirrors the MVP Entry TypeScript type exactly — 4 fields, node_id included
    because the frontend generates it with crypto.randomUUID().
    created_at is expected as YYYY-MM-DD from the frontend; the service enriches
    it with the current time before writing to disk.
    """

    node_id: str = Field(..., description="UUID generated by the frontend")
    title_or_name: str = Field(..., min_length=1)
    created_at: str = Field(
        ...,
        pattern=r"^\d{4}-\d{2}-\d{2}$",
        description="YYYY-MM-DD from the date picker",
    )
    body_text: str = Field(..., min_length=1)
