from pydantic import BaseModel, Field


class EntryCreate(BaseModel):
    """
    Pydantic model for the POST /entries request body.
    Mirrors the MVP Entry TypeScript type exactly — 4 fields, node_id included
    because the frontend generates it with crypto.randomUUID().
    """

    node_id: str = Field(..., description="UUID generated by the frontend")
    title_or_name: str = Field(..., min_length=1)
    created_at: str = Field(
        ..., pattern=r"^\d{4}-\d{2}-\d{2}$", description="YYYY-MM-DD"
    )
    body_text: str = Field(..., min_length=1)
